# Page settings
baseurl = "accountant.nappkin.nl"
title = "Nappkin"
languageCode = "nl-NL"
theme = "hugo-elate-theme"

[params]
  
  custom_css = ["css/custom.css"]

  # Meta
  author = ""
  description = ""
  email = "info@nappkin.nl"
  # Navigation
  [params.navigation]
    brand = "Nappkin"
    home = ""
    work = "Koppelingen"
    testimonials = "Testimonials"
    services = "Kenmerken"
    about = "Over"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "Complete point-of -sale oplossing voor de horeca"
    subtitle = 'Another free HTML5 bootstrap template by <a href="http://freehtml5.co/" target="_blank" title="Free HTML5 Bootstrap Templates">FREEHTML5.co</a> released under <a href="http://creativecommons.org/licenses/by/3.0/" target="_blank">Creative Commons 3.0</a><br> ported for Hugo by <a href="http://saey55.gitlab.io/pietercv" target="_blank">Pieter Saey</a>'
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Plan"
    description = "Complete Saas point-of-sale oplossing voor iPad of iPhone, vanaf €9 per maand."
    url = "#"
    button = ""
    icon = "icon-bulb"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Pin"
    description = "Geintegreerd met kaartlezers van <a href='http://paqar.nl' targt='_blank'>Paqar</a> en <a href='http://sumup.nl/nappkin' target='_blank'>Sumup</a>"
    url = "#"
    button = "Why us?"
    icon = "icon-credit-card"
    img = "img_10.jpg"

  [[params.intro.item]]
    title = "Reserveringen"
    description = "Volledige reserveringsmodule met website widget, custom emails, sms reminders etc"
    url = "#"
    button = "Click Me"
    icon = "icon-calendar"
    img = "img_8.jpg"

  [params.intro.video]
    enable = false
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"


  # Work section
  [params.work]
    enable = true
    title = "Koppelingen"
    description = "Koppeling met alle bekende boekhoudpakketten"
    footertext = ''

    [[params.work.row]]
      img = "exact_logo_300.png"
      alt = "Exact Online"
      title = "Exact"
      subtitle = ""

    [[params.work.row]]
      img = "twinfield_logo.png"
      alt = "Twinfield"
      title = "Twinfield"
      subtitle = ""

    [[params.work.row]]
      img = "snelstart_logo.png"
      alt = "Snelstart"
      title = "Snelstart"
      subtitle = ""

    [[params.work.row]]
      img = "yuki_logo_300.png"
      alt = "Yuki"
      title = "Yuki"
      subtitle = ""

    [[params.work.row]]
      img = "accountview_logo_300.png"
      alt = "Visma AccountView"
      title = "AccountView"
      subtitle = ""

    [[params.work.row]]
      img = "muis_logo.png"
      alt = "iMuis"
      title = "Muis"
      subtitle = ""

    [[params.work.row]]
      img = "multivers_logo.png"
      alt = "Unit4 Multivers"
      title = "Multivers"
      subtitle = ""

    [[params.work.row]]
      img = "minox_logo.svg"
      alt = "Minox"
      title = "Minox"
      subtitle = ""

  # Testimonials section
  [params.testimonials]
    enable = false
    title = "Testimonials"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;"
      person = 'Jean Doe, CEO <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;"
      person = 'John Doe, Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
      person = 'Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person3.jpg"
      alt = "Person3"
    



  # Services section
  [params.services]
    enable = true
    title = "Kenmerken"
    description = "Nappkin is etc"

    [[params.services.item]]
      title = "Rapportages"
      description = "Via  de my.nappkin website heb je toegang tot btw- en omzetrapportages"
      icon = "icon-globe"

    [[params.services.item]]
      title = "Email"
      description = "Wekelijks of maandelijkse email met journaalpost en statistische gegevens"
      icon = "icon-envelope"

    [[params.services.item]]
      title = "Data"
      description = "Data op bestelregel niveau t downloaden"
      icon = "icon-cloud-download"

    [[params.services.item]]
      title = "Kassa tellen"
      description = "Vastlegging kasopnames met van alles en nog wat n nog wat mer tekst voorde linebreak"
      icon = "icon-money"

  # About section
  [params.about]
    enable = false
    title = "About"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.about.item]]
      name = "Website"
      position = "Web Designer"
      description = "Op de my.nappkin website heb je toegang tot rekeningen, statistieken"
      img = "website.png"
      alt = "Person1"
      social = [
      ]

    [[params.about.item]]
      name = "Rob Smith"
      position = "Web Developer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person2.jpg"
      alt = "Person2"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-github", "#"]
      ]

    [[params.about.item]]
      name = "Larry Ben"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person3.jpg"
      alt = "Person3"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-dribbble", "#"]
      ]      

  # Counters section
  [params.counters]
    enable = true
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Bestelregels"
      icon = "icon-cup"
      from = 0
      to = 9734595
      interval = 200
      speed = 5000

    [[params.counters.item]]
      description = "Rekeningen"
      icon = "icon-file"
      from = 0
      to = 2338984
      interval = 100
      speed = 5000

    [[params.counters.item]]
      description = "Reserveringen"
      icon = "icon-calendar"
      from = 0
      to = 167423
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Gasten"
      icon = "icon-people"
      from = 0
      to = 1117290
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = false
    form = true
    title = "Contact"
    description = ""
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "Warmoesstraat 111, 1012 JA Amsterdam"],
        ["icon-phone", "020-4287777"],
        ["icon-envelope", "info@nappkin.nl"],
        ["icon-globe", '<a href="http://nappkin.nl/" target="_blank">nappkin.nl</a>']
      ]

    name = "Naam"
    email = "Email"
    phone = "Telefoon"
    message = "Bericht"
    button = "Verstuur"

  # Footer section
  [params.footer]
    enable = false
    copyright = '&copy; Elate Free HTML5. All Rights Reserved. <br>Created by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> Images: <a href="http://pexels.com/" target="_blank">Pexels</a>, <a href="http://plmd.me/" target="_blank">plmd.me</a> <br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a>'
    links = [
        ["icon-twitter", "#twitter"],
        ["icon-facebook", "#facebook"],
        ["icon-youtube", "#youtube"]
      ]
